# Generated by Django 2.1.1 on 2019-03-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0002_remove_madeira_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='madeira',
            name='observacoes',
            field=models.TextField(default='', verbose_name='Observações'),
        ),
    ]
