# Generated by Django 2.1.1 on 2019-03-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0003_madeira_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True, verbose_name='Titulo')),
                ('texto', models.TextField(default='', verbose_name='Texto')),
            ],
        ),
    ]
