# Generated by Django 2.1.1 on 2019-03-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0005_auto_20190317_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedDeNoticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Titulo')),
                ('text', models.TextField(default='', verbose_name='Texto')),
                ('image', models.ImageField(null=True, upload_to='noticiasImages', verbose_name='Imagem')),
            ],
        ),
    ]
