# Generated by Django 2.1.1 on 2019-03-17 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0006_feeddenoticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeddenoticias',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feeddenoticias',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
