# Generated by Django 2.1.1 on 2019-03-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0007_auto_20190317_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeddenoticias',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='noticiasImages', verbose_name='Imagem'),
        ),
    ]
