# Generated by Django 2.1.1 on 2019-03-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0009_colaboradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='Email'),
        ),
    ]
